services:
  web:
    container_name: floorplan-app
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "
        # python manage.py makemigrations &&
        # python manage.py migrate &&
        # python manage.py populate_db &&
        # python manage.py collectstatic &&
        daphne floorplan_service.asgi:application -b 0.0.0.0 -p 8000
      "
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - redis

  redis:
    container_name: floorplan-app-redis
    image: redis:latest

  celery:
    container_name: floorplan-app-celery
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "
        echo 'Waiting for floorplan-app and redis...';
        while ! nc -z floorplan-app 8000 || ! nc -z redis 6379; do
          sleep 1;
        done;
        echo 'Web and Redis are up - starting celery worker';
        celery -A floorplan_service worker --loglevel=info;
      "
    volumes:
      - .:/code
    depends_on:
      - redis
