# Generated by Django 4.2.20 on 2025-03-13 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AllFloorsData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("json_file_url", models.URLField()),
                ("csv_url", models.URLField()),
                ("total_area_csv_url", models.URLField()),
                ("image_labelme_side_by_side_url", models.URLField()),
                ("notes", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="CsvFloor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("floor_name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "calculated_total_area_metric",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "calculated_total_area_imperial",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "all_floors_data",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="csv_floors",
                        to="floorplan.allfloorsdata",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CsvRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("room_name", models.CharField(blank=True, max_length=100, null=True)),
                ("is_segment", models.CharField(blank=True, max_length=50, null=True)),
                ("room_id", models.FloatField(blank=True, null=True)),
                ("no_of_doors", models.FloatField(blank=True, null=True)),
                ("no_of_windows", models.FloatField(blank=True, null=True)),
                ("no_of_room_points", models.FloatField(blank=True, null=True)),
                (
                    "floor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rooms",
                        to="floorplan.csvfloor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FloorPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("floorplan_id", models.CharField(max_length=255)),
                ("original_url", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="FloorPlanAnalysisResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.CharField(max_length=255)),
                ("user_id", models.CharField(max_length=255)),
                ("property_id", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="PlanFloor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("floor", models.CharField(max_length=255)),
                ("label_me_url", models.URLField()),
                ("json_file_url", models.URLField()),
                ("image_url", models.URLField()),
                ("labelme_image_url", models.URLField()),
                ("csv_url", models.URLField()),
                ("image_side_by_side_url", models.URLField()),
                (
                    "floor_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plan_floors",
                        to="floorplan.floorplan",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="floorplan",
            name="analysis_result",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="floor_plans",
                to="floorplan.floorplananalysisresult",
            ),
        ),
        migrations.CreateModel(
            name="CsvRoomScalingFactors",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scale_metric", models.FloatField(blank=True, null=True)),
                ("scale_imperial", models.FloatField(blank=True, null=True)),
                (
                    "room",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scaling_factors",
                        to="floorplan.csvroom",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CsvRoomPixelData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("min_x_pixels", models.FloatField(blank=True, null=True)),
                ("min_y_pixels", models.FloatField(blank=True, null=True)),
                ("max_x_pixels", models.FloatField(blank=True, null=True)),
                ("max_y_pixels", models.FloatField(blank=True, null=True)),
                ("max_area_pixels", models.FloatField(blank=True, null=True)),
                ("actual_area_pixels", models.FloatField(blank=True, null=True)),
                ("pixel_ratio", models.FloatField(blank=True, null=True)),
                (
                    "room",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pixel_data",
                        to="floorplan.csvroom",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CsvRoomDimensions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dimensions_imperial",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "dimensions_metric",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("max_area_metric", models.FloatField(blank=True, null=True)),
                ("max_area_imperial", models.FloatField(blank=True, null=True)),
                ("calculated_sq_area_metric", models.FloatField(blank=True, null=True)),
                (
                    "calculated_floor_total_sq_area_metric",
                    models.FloatField(blank=True, null=True),
                ),
                ("calculated_area_imperial", models.FloatField(blank=True, null=True)),
                (
                    "calculated_floor_total_sq_area_imperial",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "room",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dimensions",
                        to="floorplan.csvroom",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="allfloorsdata",
            name="floor_plan",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="all_floors_data",
                to="floorplan.floorplan",
            ),
        ),
    ]
