# Generated by Django 4.2.20 on 2025-04-11 04:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AllFloorsData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "json_file_url",
                    models.URLField(blank=True, max_length=1024, null=True),
                ),
                ("csv_url", models.URLField(blank=True, max_length=1024, null=True)),
                (
                    "total_area_csv_url",
                    models.URLField(blank=True, max_length=1024, null=True),
                ),
                (
                    "image_labelme_side_by_side_url",
                    models.URLField(blank=True, max_length=1024, null=True),
                ),
                ("notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CsvFloor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("floor_name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "calculated_total_area_metric",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "calculated_total_area_imperial",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "all_floors_data",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="csv_floors",
                        to="floorplan.allfloorsdata",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CsvRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("room_name", models.CharField(blank=True, max_length=100, null=True)),
                ("is_segment", models.CharField(blank=True, max_length=50, null=True)),
                ("room_id", models.FloatField(blank=True, db_index=True, null=True)),
                ("no_of_doors", models.FloatField(blank=True, null=True)),
                ("no_of_windows", models.FloatField(blank=True, null=True)),
                ("no_of_room_points", models.FloatField(blank=True, null=True)),
                (
                    "floor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rooms",
                        to="floorplan.csvfloor",
                    ),
                ),
            ],
            options={
                "unique_together": {("floor", "room_id")},
            },
        ),
        migrations.CreateModel(
            name="FloorPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("floorplan_id", models.CharField(db_index=True, max_length=64)),
                ("original_url", models.URLField(max_length=1024)),
                (
                    "update_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of times webhook processing updated this record.",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FloorPlanAnalysisResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("message", models.CharField(max_length=255)),
                ("user_id", models.CharField(max_length=255)),
                ("property_id", models.CharField(max_length=255)),
            ],
            options={
                "unique_together": {("user_id", "property_id")},
            },
        ),
        migrations.CreateModel(
            name="PlanFloor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("floor", models.CharField(max_length=255)),
                (
                    "label_me_url",
                    models.URLField(blank=True, max_length=1024, null=True),
                ),
                (
                    "json_file_url",
                    models.URLField(blank=True, max_length=1024, null=True),
                ),
                ("image_url", models.URLField(blank=True, max_length=1024, null=True)),
                (
                    "labelme_image_url",
                    models.URLField(blank=True, max_length=1024, null=True),
                ),
                ("csv_url", models.URLField(blank=True, max_length=1024, null=True)),
                (
                    "image_side_by_side_url",
                    models.URLField(blank=True, max_length=1024, null=True),
                ),
                (
                    "floor_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plan_floors",
                        to="floorplan.floorplan",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HistoricalTotalAreasCsvData",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("area_name", models.CharField(blank=True, max_length=500, null=True)),
                ("square_meters", models.FloatField(blank=True, null=True)),
                ("square_feet", models.FloatField(blank=True, null=True)),
                ("total_floors", models.IntegerField(blank=True, null=True)),
                ("total_named_rooms", models.IntegerField(blank=True, null=True)),
                ("total_segments", models.IntegerField(blank=True, null=True)),
                ("total_points", models.IntegerField(blank=True, null=True)),
                ("total_objects", models.IntegerField(blank=True, null=True)),
                ("total_door_objects", models.IntegerField(blank=True, null=True)),
                ("total_window_objects", models.IntegerField(blank=True, null=True)),
                ("total_stair_objects", models.IntegerField(blank=True, null=True)),
                ("list_of_objects", models.TextField(blank=True, null=True)),
                ("total_actual_pixels", models.FloatField(blank=True, null=True)),
                ("metric_scale", models.FloatField(blank=True, null=True)),
                ("imperial_scale", models.FloatField(blank=True, null=True)),
                ("input_image_tokens", models.IntegerField(blank=True, null=True)),
                ("input_text_tokens", models.IntegerField(blank=True, null=True)),
                ("output_text_tokens", models.IntegerField(blank=True, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "all_floors_data",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="floorplan.allfloorsdata",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical total areas csv data",
                "verbose_name_plural": "historical Total Area Data",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalPlanFloor",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("floor", models.CharField(max_length=255)),
                (
                    "label_me_url",
                    models.URLField(blank=True, max_length=1024, null=True),
                ),
                (
                    "json_file_url",
                    models.URLField(blank=True, max_length=1024, null=True),
                ),
                ("image_url", models.URLField(blank=True, max_length=1024, null=True)),
                (
                    "labelme_image_url",
                    models.URLField(blank=True, max_length=1024, null=True),
                ),
                ("csv_url", models.URLField(blank=True, max_length=1024, null=True)),
                (
                    "image_side_by_side_url",
                    models.URLField(blank=True, max_length=1024, null=True),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "floor_plan",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="floorplan.floorplan",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical plan floor",
                "verbose_name_plural": "historical plan floors",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalFloorPlanAnalysisResult",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("message", models.CharField(max_length=255)),
                ("user_id", models.CharField(max_length=255)),
                ("property_id", models.CharField(max_length=255)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical floor plan analysis result",
                "verbose_name_plural": "historical floor plan analysis results",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalFloorPlan",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("floorplan_id", models.CharField(db_index=True, max_length=64)),
                ("original_url", models.URLField(max_length=1024)),
                (
                    "update_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of times webhook processing updated this record.",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "analysis_result",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="floorplan.floorplananalysisresult",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical floor plan",
                "verbose_name_plural": "historical floor plans",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalCsvRoomScalingFactors",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("scale_metric", models.FloatField(blank=True, null=True)),
                ("scale_imperial", models.FloatField(blank=True, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="floorplan.csvroom",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical csv room scaling factors",
                "verbose_name_plural": "historical csv room scaling factorss",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalCsvRoomPixelData",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("min_x_pixels", models.FloatField(blank=True, null=True)),
                ("min_y_pixels", models.FloatField(blank=True, null=True)),
                ("max_x_pixels", models.FloatField(blank=True, null=True)),
                ("max_y_pixels", models.FloatField(blank=True, null=True)),
                ("max_area_pixels", models.FloatField(blank=True, null=True)),
                ("actual_area_pixels", models.FloatField(blank=True, null=True)),
                ("pixel_ratio", models.FloatField(blank=True, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="floorplan.csvroom",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical csv room pixel data",
                "verbose_name_plural": "historical csv room pixel datas",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalCsvRoomDimensions",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                (
                    "dimensions_imperial",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "dimensions_metric",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("max_area_metric", models.FloatField(blank=True, null=True)),
                ("max_area_imperial", models.FloatField(blank=True, null=True)),
                ("calculated_sq_area_metric", models.FloatField(blank=True, null=True)),
                ("calculated_area_imperial", models.FloatField(blank=True, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="floorplan.csvroom",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical csv room dimensions",
                "verbose_name_plural": "historical csv room dimensionss",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalCsvRoom",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("room_name", models.CharField(blank=True, max_length=100, null=True)),
                ("is_segment", models.CharField(blank=True, max_length=50, null=True)),
                ("room_id", models.FloatField(blank=True, db_index=True, null=True)),
                ("no_of_doors", models.FloatField(blank=True, null=True)),
                ("no_of_windows", models.FloatField(blank=True, null=True)),
                ("no_of_room_points", models.FloatField(blank=True, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "floor",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="floorplan.csvfloor",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical csv room",
                "verbose_name_plural": "historical csv rooms",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalCsvFloor",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("floor_name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "calculated_total_area_metric",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "calculated_total_area_imperial",
                    models.FloatField(blank=True, null=True),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "all_floors_data",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="floorplan.allfloorsdata",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical csv floor",
                "verbose_name_plural": "historical csv floors",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalAllFloorsData",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                (
                    "json_file_url",
                    models.URLField(blank=True, max_length=1024, null=True),
                ),
                ("csv_url", models.URLField(blank=True, max_length=1024, null=True)),
                (
                    "total_area_csv_url",
                    models.URLField(blank=True, max_length=1024, null=True),
                ),
                (
                    "image_labelme_side_by_side_url",
                    models.URLField(blank=True, max_length=1024, null=True),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "floor_plan",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="floorplan.floorplan",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical all floors data",
                "verbose_name_plural": "historical all floors datas",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalAllFloorsCsvData",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                (
                    "floor_name",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                ("room_name", models.CharField(blank=True, max_length=100, null=True)),
                ("is_segment", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "dimensions_imperial",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "dimensions_metric",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("room_id", models.FloatField(blank=True, db_index=True, null=True)),
                ("no_of_door", models.FloatField(blank=True, null=True)),
                ("no_of_window", models.FloatField(blank=True, null=True)),
                ("no_of_room_points", models.FloatField(blank=True, null=True)),
                (
                    "min_x_pixels",
                    models.FloatField(
                        blank=True, db_column="min_x_pixels_csv", null=True
                    ),
                ),
                (
                    "min_y_pixels",
                    models.FloatField(
                        blank=True, db_column="min_y_pixels_csv", null=True
                    ),
                ),
                (
                    "max_x_pixels",
                    models.FloatField(
                        blank=True, db_column="max_x_pixels_csv", null=True
                    ),
                ),
                (
                    "max_y_pixels",
                    models.FloatField(
                        blank=True, db_column="max_y_pixels_csv", null=True
                    ),
                ),
                (
                    "max_area_metric",
                    models.FloatField(
                        blank=True, db_column="max_area_metric_csv", null=True
                    ),
                ),
                (
                    "max_area_imperial",
                    models.FloatField(
                        blank=True, db_column="max_area_imperial_csv", null=True
                    ),
                ),
                (
                    "max_area_pixels",
                    models.FloatField(
                        blank=True, db_column="max_area_pixels_csv", null=True
                    ),
                ),
                (
                    "actual_area_pixels",
                    models.FloatField(
                        blank=True, db_column="actual_area_pixels_csv", null=True
                    ),
                ),
                (
                    "pixel_ratio",
                    models.FloatField(
                        blank=True, db_column="pixel_ratio_csv", null=True
                    ),
                ),
                (
                    "scale_metric",
                    models.FloatField(
                        blank=True, db_column="scale_metric_csv", null=True
                    ),
                ),
                (
                    "scale_imperial",
                    models.FloatField(
                        blank=True, db_column="scale_imperial_csv", null=True
                    ),
                ),
                (
                    "calculated_sq_area_metric",
                    models.FloatField(
                        blank=True, db_column="calculated_sq_area_metric_csv", null=True
                    ),
                ),
                (
                    "calculated_floor_total_sq_area_metric",
                    models.FloatField(
                        blank=True, db_column="calc_floor_total_metric_csv", null=True
                    ),
                ),
                (
                    "calculated_area_imperial",
                    models.FloatField(
                        blank=True, db_column="calculated_area_imperial_csv", null=True
                    ),
                ),
                (
                    "calculated_floor_total_sq_area_imperial",
                    models.FloatField(
                        blank=True, db_column="calc_floor_total_imperial_csv", null=True
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "all_floors_data",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="floorplan.allfloorsdata",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical All Floors CSV Data",
                "verbose_name_plural": "historical All Floors CSV Data",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name="floorplan",
            name="analysis_result",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="floor_plans",
                to="floorplan.floorplananalysisresult",
            ),
        ),
        migrations.CreateModel(
            name="CsvRoomScalingFactors",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("scale_metric", models.FloatField(blank=True, null=True)),
                ("scale_imperial", models.FloatField(blank=True, null=True)),
                (
                    "room",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scaling_factors",
                        to="floorplan.csvroom",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CsvRoomPixelData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("min_x_pixels", models.FloatField(blank=True, null=True)),
                ("min_y_pixels", models.FloatField(blank=True, null=True)),
                ("max_x_pixels", models.FloatField(blank=True, null=True)),
                ("max_y_pixels", models.FloatField(blank=True, null=True)),
                ("max_area_pixels", models.FloatField(blank=True, null=True)),
                ("actual_area_pixels", models.FloatField(blank=True, null=True)),
                ("pixel_ratio", models.FloatField(blank=True, null=True)),
                (
                    "room",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pixel_data",
                        to="floorplan.csvroom",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CsvRoomDimensions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dimensions_imperial",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "dimensions_metric",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("max_area_metric", models.FloatField(blank=True, null=True)),
                ("max_area_imperial", models.FloatField(blank=True, null=True)),
                ("calculated_sq_area_metric", models.FloatField(blank=True, null=True)),
                ("calculated_area_imperial", models.FloatField(blank=True, null=True)),
                (
                    "room",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dimensions",
                        to="floorplan.csvroom",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="allfloorsdata",
            name="floor_plan",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="all_floors_data",
                to="floorplan.floorplan",
            ),
        ),
        migrations.CreateModel(
            name="TotalAreasCsvData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("area_name", models.CharField(blank=True, max_length=500, null=True)),
                ("square_meters", models.FloatField(blank=True, null=True)),
                ("square_feet", models.FloatField(blank=True, null=True)),
                ("total_floors", models.IntegerField(blank=True, null=True)),
                ("total_named_rooms", models.IntegerField(blank=True, null=True)),
                ("total_segments", models.IntegerField(blank=True, null=True)),
                ("total_points", models.IntegerField(blank=True, null=True)),
                ("total_objects", models.IntegerField(blank=True, null=True)),
                ("total_door_objects", models.IntegerField(blank=True, null=True)),
                ("total_window_objects", models.IntegerField(blank=True, null=True)),
                ("total_stair_objects", models.IntegerField(blank=True, null=True)),
                ("list_of_objects", models.TextField(blank=True, null=True)),
                ("total_actual_pixels", models.FloatField(blank=True, null=True)),
                ("metric_scale", models.FloatField(blank=True, null=True)),
                ("imperial_scale", models.FloatField(blank=True, null=True)),
                ("input_image_tokens", models.IntegerField(blank=True, null=True)),
                ("input_text_tokens", models.IntegerField(blank=True, null=True)),
                ("output_text_tokens", models.IntegerField(blank=True, null=True)),
                (
                    "all_floors_data",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="total_areas_csv_data",
                        to="floorplan.allfloorsdata",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Total Area Data",
                "unique_together": {("all_floors_data", "area_name")},
            },
        ),
        migrations.CreateModel(
            name="AllFloorsCsvData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "floor_name",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                ("room_name", models.CharField(blank=True, max_length=100, null=True)),
                ("is_segment", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "dimensions_imperial",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "dimensions_metric",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("room_id", models.FloatField(blank=True, db_index=True, null=True)),
                ("no_of_door", models.FloatField(blank=True, null=True)),
                ("no_of_window", models.FloatField(blank=True, null=True)),
                ("no_of_room_points", models.FloatField(blank=True, null=True)),
                (
                    "min_x_pixels",
                    models.FloatField(
                        blank=True, db_column="min_x_pixels_csv", null=True
                    ),
                ),
                (
                    "min_y_pixels",
                    models.FloatField(
                        blank=True, db_column="min_y_pixels_csv", null=True
                    ),
                ),
                (
                    "max_x_pixels",
                    models.FloatField(
                        blank=True, db_column="max_x_pixels_csv", null=True
                    ),
                ),
                (
                    "max_y_pixels",
                    models.FloatField(
                        blank=True, db_column="max_y_pixels_csv", null=True
                    ),
                ),
                (
                    "max_area_metric",
                    models.FloatField(
                        blank=True, db_column="max_area_metric_csv", null=True
                    ),
                ),
                (
                    "max_area_imperial",
                    models.FloatField(
                        blank=True, db_column="max_area_imperial_csv", null=True
                    ),
                ),
                (
                    "max_area_pixels",
                    models.FloatField(
                        blank=True, db_column="max_area_pixels_csv", null=True
                    ),
                ),
                (
                    "actual_area_pixels",
                    models.FloatField(
                        blank=True, db_column="actual_area_pixels_csv", null=True
                    ),
                ),
                (
                    "pixel_ratio",
                    models.FloatField(
                        blank=True, db_column="pixel_ratio_csv", null=True
                    ),
                ),
                (
                    "scale_metric",
                    models.FloatField(
                        blank=True, db_column="scale_metric_csv", null=True
                    ),
                ),
                (
                    "scale_imperial",
                    models.FloatField(
                        blank=True, db_column="scale_imperial_csv", null=True
                    ),
                ),
                (
                    "calculated_sq_area_metric",
                    models.FloatField(
                        blank=True, db_column="calculated_sq_area_metric_csv", null=True
                    ),
                ),
                (
                    "calculated_floor_total_sq_area_metric",
                    models.FloatField(
                        blank=True, db_column="calc_floor_total_metric_csv", null=True
                    ),
                ),
                (
                    "calculated_area_imperial",
                    models.FloatField(
                        blank=True, db_column="calculated_area_imperial_csv", null=True
                    ),
                ),
                (
                    "calculated_floor_total_sq_area_imperial",
                    models.FloatField(
                        blank=True, db_column="calc_floor_total_imperial_csv", null=True
                    ),
                ),
                (
                    "all_floors_data",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="all_floors_csv_data",
                        to="floorplan.allfloorsdata",
                    ),
                ),
            ],
            options={
                "verbose_name": "All Floors CSV Data",
                "verbose_name_plural": "All Floors CSV Data",
                "indexes": [
                    models.Index(
                        fields=["all_floors_data", "floor_name"],
                        name="floorplan_a_all_flo_7c5683_idx",
                    ),
                    models.Index(
                        fields=["all_floors_data", "room_id"],
                        name="floorplan_a_all_flo_7641e2_idx",
                    ),
                ],
            },
        ),
    ]
