# Generated by Django 4.2.20 on 2025-04-16 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("floorplan", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="floorplan",
            options={
                "verbose_name": "Floor Plan",
                "verbose_name_plural": "Floor Plans",
            },
        ),
        migrations.AlterModelOptions(
            name="floorplananalysisresult",
            options={
                "verbose_name": "Floor Plan Analysis Result",
                "verbose_name_plural": "Floor Plan Analysis Results",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalfloorplan",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Floor Plan",
                "verbose_name_plural": "historical Floor Plans",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalfloorplananalysisresult",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Floor Plan Analysis Result",
                "verbose_name_plural": "historical Floor Plan Analysis Results",
            },
        ),
        migrations.AlterModelOptions(
            name="historicaltotalareascsvdata",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Total Area CSV Data",
                "verbose_name_plural": "historical Total Area CSV Data",
            },
        ),
        migrations.AlterModelOptions(
            name="totalareascsvdata",
            options={
                "verbose_name": "Total Area CSV Data",
                "verbose_name_plural": "Total Area CSV Data",
            },
        ),
        migrations.RenameField(
            model_name="csvroom",
            old_name="floor",
            new_name="csv_floor",
        ),
        migrations.RenameField(
            model_name="csvroomdimensions",
            old_name="room",
            new_name="csv_room",
        ),
        migrations.RenameField(
            model_name="csvroompixeldata",
            old_name="room",
            new_name="csv_room",
        ),
        migrations.RenameField(
            model_name="csvroomscalingfactors",
            old_name="room",
            new_name="csv_room",
        ),
        migrations.RenameField(
            model_name="historicalcsvroom",
            old_name="floor",
            new_name="csv_floor",
        ),
        migrations.RenameField(
            model_name="historicalcsvroomdimensions",
            old_name="room",
            new_name="csv_room",
        ),
        migrations.RenameField(
            model_name="historicalcsvroompixeldata",
            old_name="room",
            new_name="csv_room",
        ),
        migrations.RenameField(
            model_name="historicalcsvroomscalingfactors",
            old_name="room",
            new_name="csv_room",
        ),
        migrations.AlterUniqueTogether(
            name="csvroom",
            unique_together={("csv_floor", "room_id")},
        ),
        migrations.AlterUniqueTogether(
            name="floorplan",
            unique_together={("analysis_result", "floorplan_id")},
        ),
        migrations.AddIndex(
            model_name="floorplan",
            index=models.Index(
                fields=["floorplan_id"], name="floorplan_f_floorpl_55f044_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="floorplananalysisresult",
            index=models.Index(
                fields=["user_id", "property_id"], name="floorplan_f_user_id_caabf3_idx"
            ),
        ),
    ]
