# Generated by Django 4.2.20 on 2025-04-04 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("floorplan", "0002_historicalplanfloor_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="csvroomdimensions",
            name="calculated_floor_total_sq_area_imperial",
        ),
        migrations.RemoveField(
            model_name="csvroomdimensions",
            name="calculated_floor_total_sq_area_metric",
        ),
        migrations.RemoveField(
            model_name="historicalcsvroomdimensions",
            name="calculated_floor_total_sq_area_imperial",
        ),
        migrations.RemoveField(
            model_name="historicalcsvroomdimensions",
            name="calculated_floor_total_sq_area_metric",
        ),
        migrations.AlterUniqueTogether(
            name="floorplan",
            unique_together={("analysis_result", "floorplan_id")},
        ),
        migrations.AlterUniqueTogether(
            name="floorplananalysisresult",
            unique_together={("user_id", "property_id")},
        ),
        migrations.CreateModel(
            name="HistoricalTotalAreaData",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("area_name", models.CharField(blank=True, max_length=500, null=True)),
                ("square_meters", models.FloatField(blank=True, null=True)),
                ("square_feet", models.FloatField(blank=True, null=True)),
                ("total_floors", models.IntegerField(blank=True, null=True)),
                ("total_named_rooms", models.IntegerField(blank=True, null=True)),
                ("total_segments", models.IntegerField(blank=True, null=True)),
                ("total_points", models.IntegerField(blank=True, null=True)),
                ("total_objects", models.IntegerField(blank=True, null=True)),
                ("total_door_objects", models.IntegerField(blank=True, null=True)),
                ("total_window_objects", models.IntegerField(blank=True, null=True)),
                ("total_stair_objects", models.IntegerField(blank=True, null=True)),
                ("list_of_objects", models.TextField(blank=True, null=True)),
                ("total_actual_pixels", models.FloatField(blank=True, null=True)),
                ("metric_scale", models.FloatField(blank=True, null=True)),
                ("imperial_scale", models.FloatField(blank=True, null=True)),
                ("input_image_tokens", models.IntegerField(blank=True, null=True)),
                ("input_text_tokens", models.IntegerField(blank=True, null=True)),
                ("output_text_tokens", models.IntegerField(blank=True, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "all_floors_data",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="floorplan.allfloorsdata",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical total area data",
                "verbose_name_plural": "historical Total Area Data",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalAllFloorsCsvRawRow",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "floor_name",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                ("room_name", models.CharField(blank=True, max_length=100, null=True)),
                ("is_segment", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "dimensions_imperial",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "dimensions_metric",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("room_id", models.FloatField(blank=True, db_index=True, null=True)),
                ("no_of_door", models.FloatField(blank=True, null=True)),
                ("no_of_window", models.FloatField(blank=True, null=True)),
                ("no_of_room_points", models.FloatField(blank=True, null=True)),
                (
                    "min_x_pixels",
                    models.FloatField(
                        blank=True, db_column="min_x_pixels_csv", null=True
                    ),
                ),
                (
                    "min_y_pixels",
                    models.FloatField(
                        blank=True, db_column="min_y_pixels_csv", null=True
                    ),
                ),
                (
                    "max_x_pixels",
                    models.FloatField(
                        blank=True, db_column="max_x_pixels_csv", null=True
                    ),
                ),
                (
                    "max_y_pixels",
                    models.FloatField(
                        blank=True, db_column="max_y_pixels_csv", null=True
                    ),
                ),
                (
                    "max_area_metric",
                    models.FloatField(
                        blank=True, db_column="max_area_metric_csv", null=True
                    ),
                ),
                (
                    "max_area_imperial",
                    models.FloatField(
                        blank=True, db_column="max_area_imperial_csv", null=True
                    ),
                ),
                (
                    "max_area_pixels",
                    models.FloatField(
                        blank=True, db_column="max_area_pixels_csv", null=True
                    ),
                ),
                (
                    "actual_area_pixels",
                    models.FloatField(
                        blank=True, db_column="actual_area_pixels_csv", null=True
                    ),
                ),
                (
                    "pixel_ratio",
                    models.FloatField(
                        blank=True, db_column="pixel_ratio_csv", null=True
                    ),
                ),
                (
                    "scale_metric",
                    models.FloatField(
                        blank=True, db_column="scale_metric_csv", null=True
                    ),
                ),
                (
                    "scale_imperial",
                    models.FloatField(
                        blank=True, db_column="scale_imperial_csv", null=True
                    ),
                ),
                (
                    "calculated_sq_area_metric",
                    models.FloatField(
                        blank=True, db_column="calculated_sq_area_metric_csv", null=True
                    ),
                ),
                (
                    "calculated_floor_total_sq_area_metric",
                    models.FloatField(
                        blank=True, db_column="calc_floor_total_metric_csv", null=True
                    ),
                ),
                (
                    "calculated_area_imperial",
                    models.FloatField(
                        blank=True, db_column="calculated_area_imperial_csv", null=True
                    ),
                ),
                (
                    "calculated_floor_total_sq_area_imperial",
                    models.FloatField(
                        blank=True, db_column="calc_floor_total_imperial_csv", null=True
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "all_floors_data",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="floorplan.allfloorsdata",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical All Floors CSV Raw Row",
                "verbose_name_plural": "historical All Floors CSV Raw Rows",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="TotalAreaData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("area_name", models.CharField(blank=True, max_length=500, null=True)),
                ("square_meters", models.FloatField(blank=True, null=True)),
                ("square_feet", models.FloatField(blank=True, null=True)),
                ("total_floors", models.IntegerField(blank=True, null=True)),
                ("total_named_rooms", models.IntegerField(blank=True, null=True)),
                ("total_segments", models.IntegerField(blank=True, null=True)),
                ("total_points", models.IntegerField(blank=True, null=True)),
                ("total_objects", models.IntegerField(blank=True, null=True)),
                ("total_door_objects", models.IntegerField(blank=True, null=True)),
                ("total_window_objects", models.IntegerField(blank=True, null=True)),
                ("total_stair_objects", models.IntegerField(blank=True, null=True)),
                ("list_of_objects", models.TextField(blank=True, null=True)),
                ("total_actual_pixels", models.FloatField(blank=True, null=True)),
                ("metric_scale", models.FloatField(blank=True, null=True)),
                ("imperial_scale", models.FloatField(blank=True, null=True)),
                ("input_image_tokens", models.IntegerField(blank=True, null=True)),
                ("input_text_tokens", models.IntegerField(blank=True, null=True)),
                ("output_text_tokens", models.IntegerField(blank=True, null=True)),
                (
                    "all_floors_data",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="total_area_data",
                        to="floorplan.allfloorsdata",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Total Area Data",
                "unique_together": {("all_floors_data", "area_name")},
            },
        ),
        migrations.CreateModel(
            name="AllFloorsCsvRawRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "floor_name",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                ("room_name", models.CharField(blank=True, max_length=100, null=True)),
                ("is_segment", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "dimensions_imperial",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "dimensions_metric",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("room_id", models.FloatField(blank=True, db_index=True, null=True)),
                ("no_of_door", models.FloatField(blank=True, null=True)),
                ("no_of_window", models.FloatField(blank=True, null=True)),
                ("no_of_room_points", models.FloatField(blank=True, null=True)),
                (
                    "min_x_pixels",
                    models.FloatField(
                        blank=True, db_column="min_x_pixels_csv", null=True
                    ),
                ),
                (
                    "min_y_pixels",
                    models.FloatField(
                        blank=True, db_column="min_y_pixels_csv", null=True
                    ),
                ),
                (
                    "max_x_pixels",
                    models.FloatField(
                        blank=True, db_column="max_x_pixels_csv", null=True
                    ),
                ),
                (
                    "max_y_pixels",
                    models.FloatField(
                        blank=True, db_column="max_y_pixels_csv", null=True
                    ),
                ),
                (
                    "max_area_metric",
                    models.FloatField(
                        blank=True, db_column="max_area_metric_csv", null=True
                    ),
                ),
                (
                    "max_area_imperial",
                    models.FloatField(
                        blank=True, db_column="max_area_imperial_csv", null=True
                    ),
                ),
                (
                    "max_area_pixels",
                    models.FloatField(
                        blank=True, db_column="max_area_pixels_csv", null=True
                    ),
                ),
                (
                    "actual_area_pixels",
                    models.FloatField(
                        blank=True, db_column="actual_area_pixels_csv", null=True
                    ),
                ),
                (
                    "pixel_ratio",
                    models.FloatField(
                        blank=True, db_column="pixel_ratio_csv", null=True
                    ),
                ),
                (
                    "scale_metric",
                    models.FloatField(
                        blank=True, db_column="scale_metric_csv", null=True
                    ),
                ),
                (
                    "scale_imperial",
                    models.FloatField(
                        blank=True, db_column="scale_imperial_csv", null=True
                    ),
                ),
                (
                    "calculated_sq_area_metric",
                    models.FloatField(
                        blank=True, db_column="calculated_sq_area_metric_csv", null=True
                    ),
                ),
                (
                    "calculated_floor_total_sq_area_metric",
                    models.FloatField(
                        blank=True, db_column="calc_floor_total_metric_csv", null=True
                    ),
                ),
                (
                    "calculated_area_imperial",
                    models.FloatField(
                        blank=True, db_column="calculated_area_imperial_csv", null=True
                    ),
                ),
                (
                    "calculated_floor_total_sq_area_imperial",
                    models.FloatField(
                        blank=True, db_column="calc_floor_total_imperial_csv", null=True
                    ),
                ),
                (
                    "all_floors_data",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="all_floors_raw_rows",
                        to="floorplan.allfloorsdata",
                    ),
                ),
            ],
            options={
                "verbose_name": "All Floors CSV Raw Row",
                "verbose_name_plural": "All Floors CSV Raw Rows",
                "indexes": [
                    models.Index(
                        fields=["all_floors_data", "floor_name"],
                        name="floorplan_a_all_flo_aed215_idx",
                    ),
                    models.Index(
                        fields=["all_floors_data", "room_id"],
                        name="floorplan_a_all_flo_be2d1f_idx",
                    ),
                ],
            },
        ),
    ]
